# Generated by Django 5.1.5 on 2025-08-10 06:03

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCompanyModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_created=True)),
                ('course_company_name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(upload_to='profile_photo')),
            ],
        ),
        migrations.CreateModel(
            name='CourseLanguageModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_created=True)),
                ('language_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('level', models.CharField(choices=[('A0', 'A0'), ('A1', 'A1'), ('A2', 'A2'), ('A1-A2', 'A1-A2'), ('B1', 'B1'), ('B2', 'B2'), ('B1-B2', 'B1-B2'), ('C1', 'C1')], max_length=25)),
                ('time', models.TimeField(blank=True, null=True)),
                ('price', models.PositiveIntegerField()),
                ('connect_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language', to='course.coursecompanymodels')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LessonModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_created=True)),
                ('lesson_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('lesson_material', models.FileField(upload_to='lesson_material')),
                ('connect_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='course.courselanguagemodels')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('status', models.CharField(choices=[('student', 'student'), ('teacher', 'teacher')], default='student', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Student',
            },
            bases=('course.userprofile',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('status', models.CharField(choices=[('student', 'student'), ('teacher', 'teacher')], default='teacher', max_length=100)),
                ('experience', models.CharField(max_length=64)),
                ('about_teacher', models.TextField()),
                ('specialization', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name_plural': 'Teacher',
            },
            bases=('course.userprofile',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.DeleteModel(
            name='CourseCompanyModel',
        ),
        migrations.AddField(
            model_name='lessonmodels',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='course.teacher'),
        ),
        migrations.AddField(
            model_name='coursecompanymodels',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='course.teacher'),
        ),
    ]
