# Generated by Django 5.1.5 on 2025-08-10 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_coursecompanymodels_courselanguagemodels_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courselanguagemodels',
            old_name='time',
            new_name='time_end',
        ),
        migrations.AddField(
            model_name='courselanguagemodels',
            name='time_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
